const tour = [
    {
        id: 1,
        title: "Three Temples Bangkok City Tour Must Visit",
        category: "New York",
        price: 149.99,
        img: "img/tour-1.png",
    },
    {
        id: 2,
        title: "Essence of Vietnam South to North",
        category: "New York",
        price: 167.19,
        img: "img/tour-2.png",
        special: true,
    },
    {
        id: 3,
        title: "Osa Peninsula to Dominical City Tour",
        category: "New York",
        price: 134.99,
        img: "img/tour-3.png",
    },
    {
        id: 4,
        title: "Mt Fuji, Hakone, Lake Ashi Cruise",
        category: "New York",
        price: 50.15,
        img: "img/tour-4.png",
        special: true,
    },
    {
        id: 5,
        title: "Three Temples Bangkok City Tour Must Visit",
        category: "London",
        price: 149.99,
        img: "img/tour-5.png",
    },
    {
        id: 6,
        title: "Essence of Vietnam South to North",
        category: "London",
        price: 167.19,
        img: "img/tour-6.png",
    },
    {
        id: 7,
        title: "Osa Peninsula to Dominical City Tour",
        category: "London",
        price: 134.99,
        img: "img/tour-7.png",
        special: true,
    },
    {
        id: 8,
        title: "Mt Fuji, Hakone, Lake Ashi Cruise",
        category: "London",
        price: 50.15,
        img: "img/tour-8.png",
    },
    {
        id: 9,
        title: "Three Temples Bangkok City Tour Must Visit",
        category: "Tokyo",
        price: 149.99,
        img: "img/tour-9.png",
        special: true,
    },
    {
        id: 10,
        title: "Essence of Vietnam South to North",
        category: "Tokyo",
        price: 117.19,
        img: "img/tour-10.png",
    },
    {
        id: 11,
        title: "Osa Peninsula to Dominical City Tour",
        category: "Tokyo",
        price: 134.99,
        img: "img/tour-11.png",
    },
    {
        id: 12,
        title: "Mt Fuji, Hakone, Lake Ashi Cruise",
        category: "Tokyo",
        price: 50.15,
        img: "img/tour-12.png",
    },
    {
        id: 13,
        title: "Three Temples Bangkok City Tour Must Visit",
        category: "Los Angeles",
        price: 149.99,
        img: "img/tour-13.png",
    },
    {
        id: 14,
        title: "Essence of Vietnam South to North",
        category: "Los Angeles",
        price: 117.19,
        img: "img/tour-14.png",
    },
    {
        id: 15,
        title: "Osa Peninsula to Dominical City Tour",
        category: "Los Angeles",
        price: 134.99,
        img: "img/tour-15.png",
    },
    {
        id: 16,
        title: "Mt Fuji, Hakone, Lake Ashi Cruise",
        category: "Los Angeles",
        price: 50.15,
        img: "img/tour-16.png",
    },
];
export default tour;
